[mypy]
explicit_package_bases = True
mypy_path = .
implicit_optional = True
plugins = pydantic.mypy
exclude = ^backend[\\/](scripts|tests)[\\/]

[mypy-backend.tests.*]
ignore_errors = True

[mypy-backend.scripts.*]
ignore_errors = True
