bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
databases 16

loglevel notice
logfile ""

save 900 1
save 300 10
save 60 10000

appendonly yes
appendfsync everysec

maxmemory 256mb
maxmemory-policy allkeys-lru

dir /data
